# Generated by Django 3.1.6 on 2021-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_title', models.TextField(default='', verbose_name='题目图片')),
                ('pic_answer', models.TextField(default='', verbose_name='答案图片')),
                ('origin_id', models.IntegerField(verbose_name='原id')),
                ('origin_type', models.CharField(default='section', max_length=20, verbose_name='题目类型')),
                ('version', models.PositiveIntegerField(default='0', verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '语文题集',
                'verbose_name_plural': '语文题集',
                'db_table': 'questions_chinese',
            },
        ),
        migrations.CreateModel(
            name='EnglishQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_title', models.TextField(default='', verbose_name='题目图片')),
                ('pic_answer', models.TextField(default='', verbose_name='答案图片')),
                ('origin_id', models.IntegerField(verbose_name='原id')),
                ('origin_type', models.CharField(default='section', max_length=20, verbose_name='题目类型')),
                ('version', models.PositiveIntegerField(default='0', verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '英文题集',
                'verbose_name_plural': '英文题集',
                'db_table': 'questions_english',
            },
        ),
    ]
