# Generated by Django 3.1.6 on 2021-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesequestion',
            name='origin_id',
            field=models.IntegerField(default='0', verbose_name='原id'),
        ),
        migrations.AlterField(
            model_name='chinesequestion',
            name='version',
            field=models.IntegerField(default='0', verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='englishquestion',
            name='origin_id',
            field=models.IntegerField(default='0', verbose_name='原id'),
        ),
        migrations.AlterField(
            model_name='englishquestion',
            name='version',
            field=models.IntegerField(default='0', verbose_name='版本'),
        ),
    ]
