# Generated by Django 3.1.6 on 2021-03-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210303_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinesequestion',
            name='step',
            field=models.IntegerField(default='1', verbose_name='步骤'),
        ),
        migrations.AddField(
            model_name='chinesequestion',
            name='text_answer',
            field=models.TextField(default='', verbose_name='答案文本'),
        ),
        migrations.AddField(
            model_name='chinesequestion',
            name='text_title',
            field=models.TextField(default='', verbose_name='题目文本'),
        ),
        migrations.AddField(
            model_name='englishquestion',
            name='step',
            field=models.IntegerField(default='1', verbose_name='步骤'),
        ),
        migrations.AddField(
            model_name='englishquestion',
            name='text_answer',
            field=models.TextField(default='', verbose_name='答案文本'),
        ),
        migrations.AddField(
            model_name='englishquestion',
            name='text_title',
            field=models.TextField(default='', verbose_name='题目文本'),
        ),
    ]
