# Generated by Django 3.1.6 on 2021-03-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210305_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesequestion',
            name='pic_answer',
            field=models.CharField(default='', max_length=200, verbose_name='答案图片'),
        ),
        migrations.AlterField(
            model_name='chinesequestion',
            name='pic_title',
            field=models.CharField(default='', max_length=200, verbose_name='题目图片'),
        ),
        migrations.AlterField(
            model_name='chinesequestion',
            name='same_guids',
            field=models.TextField(default='', max_length=200, verbose_name='同类题guid'),
        ),
        migrations.AlterField(
            model_name='englishquestion',
            name='pic_answer',
            field=models.CharField(default='', max_length=200, verbose_name='答案图片'),
        ),
        migrations.AlterField(
            model_name='englishquestion',
            name='pic_title',
            field=models.CharField(default='', max_length=200, verbose_name='题目图片'),
        ),
        migrations.AlterField(
            model_name='englishquestion',
            name='same_guids',
            field=models.TextField(default='', max_length=200, verbose_name='同类题guid'),
        ),
    ]
