mysql-demo:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./config/master.mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root
      - MYSQL_DATABASE=test
