# Generated by Django 3.1.6 on 2021-04-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SameSectionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.TextField(default='', verbose_name='guid')),
                ('sectiontitle', models.TextField(default='', verbose_name='题目图片')),
                ('sectionanswer', models.TextField(default='', verbose_name='答案图片')),
            ],
            options={
                'db_table': 'W_SameSectionInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionInfo',
            fields=[
                ('id_inc', models.AutoField(primary_key=True, serialize=False)),
                ('sectiontitle', models.TextField(default='', verbose_name='题目图片')),
                ('sectionkey', models.TextField(default='', verbose_name='答案图片')),
                ('subjectid', models.IntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '物理')], default='0', verbose_name='学科id')),
                ('samesectiondata', models.TextField(default='', verbose_name='同类题id')),
            ],
            options={
                'db_table': 'W_SectionInfo',
                'managed': False,
            },
        ),
    ]
